---
- name: set mysql root password
  mysql_user: name=root host=localhost password={{ password }}
              login_user=root login_password={{ password }}
              check_implicit_admin=yes
  tags: mysqld

- name: set mysql root password
  mysql_user: name=root host={{ item }} password={{ password }}
              login_user=root login_password={{ password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
  tags: mysqld
